### ISSUE TITLE
React 16 – Refs Must Have Owner Warning

### ISSUE THREAD

**Issue by foaly-nr1** [raphasilvac/react-simple-contenteditable#2]
Using this component with React 16 leads to a [Refs Must Have Owner Warning](https://fb.me/react-refs-must-have-owner):

> **Warning:**
> Element ref was specified as a string (myRefName) but no owner was set. You may have multiple copies of React loaded. (details: https://fb.me/react-refs-must-have-owner).

**Comment by raphasilvac** [comment]
Hello @foaly-nr1, 
I think it was fixed in the version 0.0.3.
Pls, can you try it again?
Thanks!

**Comment by foaly-nr1** [comment]
Where do I find 0.0.3?
> 0.0.1 is the latest release
— https://www.npmjs.com/package/react-simple-contenteditable

**Comment by raphasilvac** [comment]
Hello @foaly-nr1,
Sorry, I updated npm registry right now.
Thanks!
